/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   {
  //     type: 'doc',
  //     label: 'はじめに',
  //     id : 'intro',
  //   },
  //   {
  //     type: 'doc',
  //     label: '導入方法',
  //     id : 'install',
  //   },
  //   {
  //     type: 'doc',
  //     label: '調整方法',
  //     id : 'setup',
  //   },
  //   {
  //     type: 'doc',
  //     label: '追加機能',
  //     id : 'addition',
  //   },
  //   {
  //     type: 'doc',
  //     label: '困ったときは',
  //     id : 'trouble',
  //   },
  // ],
};
